SSH password: 
ERROR! 'loop' is not a valid attribute for a Block
The error appears to be in '/runner/project/sccm_start_stop.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  tasks:
    - name: Perform service actions on each item
      ^ here

- name: Handle Windows service actions
  hosts: all
  gather_facts: no
  vars:
    service_list: ["Spooler", "BITS"]
    service_action: restart

  tasks:
    - name: Perform service actions on each item
      block:
        - name: Stop service {{ item }}
          ansible.windows.win_service:
            name: "{{ item }}"
            state: stopped
          when: service_action in ['stop', 'restart']

        - name: Wait 5 seconds before starting service {{ item }}
          pause:
            seconds: 5
          when: service_action == 'restart'

        - name: Start service {{ item }}
          ansible.windows.win_service:
            name: "{{ item }}"
            state: started
          when: service_action in ['start', 'restart']

        - name: Get status of {{ item }}
          ansible.windows.win_service_info:
            name: "{{ item }}"
          register: service_status

        - name: Show final status of {{ item }}
          debug:
            msg: "{{ item }} is now {{ service_status.services[0].state }}"

      rescue:
        - name: Print failure for {{ item }}
          debug:
            msg: "❌ Failed to {{ service_action }} service: {{ item }}"

      loop: "{{ service_list }}"
      loop_control:
        label: "{{ item }}"
