---
- name: Start / Stop / Restart a Windows Service
  hosts: all
  gather_facts: false

  vars:
    service_name: ""         
    service_action: ""

  tasks:
    - name: Perform '{{ service_action }}' on {{ service_name }}
      block:

        - name: Stop service {{ service_name }}
          ansible.windows.win_service:
            name: "{{ service_name }}"
            state: stopped
          when: service_action in ['stop', 'restart']

        - name: Wait 5 seconds before starting {{ service_name }}
          pause:
            seconds: 5
          when: service_action == 'restart'

        - name: Start service {{ service_name }}
          ansible.windows.win_service:
            name: "{{ service_name }}"
            state: started
          when: service_action in ['start', 'restart']

        - name: Get status of service {{ service_name }}
          ansible.windows.win_service_info:
            name: "{{ service_name }}"
          register: service_status

        - name: Show final status of {{ service_name }}
          debug:
            msg: "{{ service_name }} is now {{ service_status.services[0].state }}"

      rescue:
        - name: Log failure for service {{ service_name }}
          debug:
            msg: "Failed to {{ service_action }} service: {{ service_name }}"
