---
- name: Provision a machine on VMWare 
  hosts: localhost 
  connection: local
  vars_files:
    - vars.yml

  roles:
    - set-api-credentials
    - assemble-ca-public-key 
    - download-kickstart-templates
    - create-and-upload-kickstart-iso
    - create-virtual-machine
    - power-on-and-wait-ssh
    - delete-kickstart-iso
    - create-snapshot
    - cleanup
